# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('buyerId', models.IntegerField()),
                ('sellerId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('dateOrder', models.DateField()),
                ('dateComplete', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=100)),
                ('pricePerUnit', models.IntegerField()),
            ],
        ),
    ]
